language: python

# newer python versions are available only on xenial
# (while some older only on trusty) Ubuntu distribution
dist: xenial
sudo: required
cache: pip

branches:
  only:
    - master

jobs:
  include:
  - name: "run test suite with python 2.7"
    python: 2.7
    dist: trusty
  - name: "run test suite with python 3.4"
    python: 3.4
    dist: trusty
  - name: "run test suite with python 3.5"
    python: 3.5
    dist: trusty
  - name: "run test suite with python 3.6"
    python: 3.6
  - name: "run test suite with python 3.7"
    python: 3.7

env:
  - CPPFLAGS=--coverage
before_install:
  - pip install --upgrade pip
install:
  - python setup.py develop
script:
  - py.test py/tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
