language: python

# newer python versions are available only on xenial
# (while some older only on trusty) Ubuntu distribution
dist: xenial
sudo: required
cache: pip

addons:
  apt:
    packages: lcov

branches:
  only:
    - master

jobs:
  include:
  - name: "run test suite with python 3.6"
    python: 3.6
  - name: "run test suite with python 3.7"
    python: 3.7
  - name: "run test suite with python 3.8"
    python: 3.8

env:
  - CPPFLAGS=--coverage
before_install:
  - pip install --upgrade pip
  - pip install https://github.com/nucleic/cppy/tarball/master
install:
  - python setup.py develop
script:
  - py.test py/tests
after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
  - lcov --list coverage.info
  # Uploading to CodeCov but excluding gcov reports
  - bash <(curl -s https://codecov.io/bash) -f "!*.gcov" -X gcov || echo "Codecov did not collect coverage reports"

