language: python

# newer python versions are available only on xenial
# (while some older only on trusty) Ubuntu distribution
dist: xenial
sudo: required
cache: pip

addons:
  apt:
    packages: lcov

branches:
  only:
    - main

jobs:
  include:
  - name: "run test suite with python 3.6 on ARM64"
    arch: arm64
    python: 3.6
  - name: "run test suite with python 3.7 on ARM64"
    arch: arm64
    python: 3.7
  - name: "run test suite with python 3.8 on ARM64"
    arch: arm64
    python: 3.8
  # ARM currently does not have 3.9, should add it later

  # added power support ppc64le arch
  - name: "run test suite with python 3.6 on PPC64le"
    arch: ppc64le
    python: 3.6
  - name: "run test suite with python 3.7 on PPC64le"
    arch: ppc64le
    python: 3.7
  - name: "run test suite with python 3.8 on PPC64le"
    arch: ppc64le
    python: 3.8
  - name: "run test suite with python 3.9 on PPC64le"
    arch: ppc64le
    python: 3.9

env:
  - CPPFLAGS=--coverage
before_install:
  - pip install --upgrade pip
  - pip install https://github.com/nucleic/cppy/tarball/main
install:
  - python setup.py develop
script:
  - python -m pytest py/tests
after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
  - lcov --list coverage.info
  # Uploading to CodeCov but excluding gcov reports
  - bash <(curl -s https://codecov.io/bash) -f "!*.gcov" -X gcov || echo "Codecov did not collect coverage reports"
